- particle/pdgid/pdgid.py
- tests/pdgid/test_pdgid.py
This makes PDGids much simpler; they are just ints with some extra printing and method attached. No need to use `.pgdid` anymore. Comparisons, negation (such as in #9 ) are naturally supported.
This should nicely complement the new Particle class being moved from DecayLanguage.
> Adding int version of PDGid

- particle/pdgid/functions.py
- particle/pdgid/pdgid.py
- tests/pdgid/test_pdgid.py
This:
* Fixes some spacing and unneeded imports
* Changes the definition of J so it is the correct, fractional values (with j_spin taking on the old integer only values). Based on the [HepPDT names here](http://lcgapp.cern.ch/project/simu/HepPDT/HepPDT.3.03.00/html/ParticleIDMethods_8cc-source.html). Note that they are incorrect claiming `sSpin` and `lSpin` do the same trick; they do not.
* Simplified and propagated docstrings to properties
* Excluding non-functions is now automatic, rather than from an exclude list.
> Change spin definition

- particle/__init__.py
You can now do:
```python
from particle import PDGID, Particle
```
I've dropped the `get_pdt_csv` function, as there is a more general example in the data readme.
> Simpler imports

- README.rst
- setup.py
For some reason the logo does not appear on PyPI for the 0.2.0 release.
I'm trying to fix that using the full path ...
> Add a Zenodo DOI tag

- particle/particle/kinematics.py
- particle/particle/particle.py
- tests/particle/test_particle.py
This PR adds the lifetime as a `Particle` property, now that https://github.com/scikit-hep/particle/pull/45/ is sorted.
A few comments/questions for discussion:
- I could also trivially add c*tau, which is a very common quantity to calculate.
- the Particle class contains `width`, `width_lower` and `width_upper`. Shall I add the lower and upper too, for the lifetime?
- And where to print this info, as for now the `describe()` method prints the width info:
```
>>> print Particle.from_pdgid(511).describe()
Name: B          ID: 511          Fullname: B0             Latex: $B^{0}$
Mass  = 5279.63 +/- 0.15 MeV
Width = 4.330e-10 +/- 1.1e-12 MeV
I (isospin)       = 1/2    G (parity)        = 0      Q (charge)       = 0
J (total angular) = 0.0    C (charge parity) = 0      P (space parity) = ? …
```
> Add lifetime to Particle class properties

- README.rst
- particle/particle/particle.py
- tests/particle/test_particle.py
Another small change to the `Particle` API, @henryiii. Seems better.
All for the imminent release 0.4.0.
> Rename Particle.bar to Particle.is_name_barred

- docs/CHANGELOG.rst
- particle/particle/enums.py
- particle/particle/particle.py
- tests/particle/test_particle.py
@henryiii, it is not clear where this property is taken from. From the PDG, I guess? I'm here adding doc and tests, extending a bit the function itself, following what seems reasonable to me. Can you point me to the PDG doc where you took `Particle.spin_type` `and `SpinType enum definitions from? Thanks.
> Doc and tests for Particle.spin_type

- README.rst
- docs/CHANGELOG.rst
- particle/particle/particle.py
- tests/particle/test_particle.py
Change of API for search methods, as per our discussion.
> Rename Particle.from_search/from_search_list to Particle.find/findall

- docs/CHANGELOG.rst
- particle/particle/particle.py
Addresses https://github.com/scikit-hep/particle/issues/82.
Now all methods called on `p = Particle.empty()` work just fine. In particular, all name-related methods are consistent.
> Handling of Particle.empty()

- README.rst
- particle/particle/particle.py
- setup.py
This PR:
* Makes `load_table(..., append=True)` append to the default table if nothing is loaded; this is consistent with the rest of particle automatically loading the default table if not loaded.
* Adds a history of table names that have been loaded (needs test)
* Adds a bit of documentation (can be expanded)
Partially addresses #102.
> Loading tables is a bit nicer now

- .ci/azure-wheel.yml
- azure-pipelines.yml
- setup.cfg
This adds sdist and universal wheels to the output. Currently only available through Azure's UI, but we could add a release pipeline to publish them on tags.
Note: We could try using the declarative `setup.cfg` instead of `setup.py`, might be interesting to try. https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files
> Produce sdist and wheel

- particle/particle/particle.py
These necessary replacements provide (full) particle names, hence the better search.
> Trivial speed-up of searches for decay file particle names

- particle/particle/particle.py
This can happen if the particle properties being queried throw exceptions for invalid inputs.
Should fix https://github.com/scikit-hep/particle/pull/123/.
> Make particle searches robust against methods returning exceptions

- README.rst
- binder/postBuild
- environment.yml
@henryiii @eduardo-rodrigues It would be great to have the demo be even more interactive by [Binderizing the repo](https://mybinder.org/). 
This PR adds Binder support by installing `particle` from `master` in the [`postBuild` stage](https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment). It also installs the `requirements-dev.txt` to make sure that if `pandas` is used in a Notebook it will be available, though as the added Binder badge in the `README` links directly into the demo Jupyter notebook this is more of a safety/future looking addition.
For a demo of what this looks like you can click on this badge which will launch the Binder of my fork: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/matthewfe …
> Add Binder support

- particle/particle/convert.py
- particle/particle/particle.py
- tests/particle/test_particle.py
This makes sure that for example for the J/psi the width is displayed by `Particle.describe()`, rather than the lifetime.
> Better display of lifetimes/widths

- .ci/azure-steps.yml
- particle/particle/convert.py
- particle/particle/kinematics.py
- particle/particle/particle.py
Addresses most of https://github.com/scikit-hep/particle/issues/108. What remains to be done is an update of the CI so that doctests are run by default. @henryiii, what would be the best way?
For the record I ran doctests on all but the `test` directories and `__main__.py` with the command
`pytest --doctest-modules --ignore-glob="*__main__.py" --ignore-glob="test*"`.
> Examples update to pass doctests

- particle/converters/bimap.py
This is necessary in order to have mappings of names, the obvious example being a mapping from/to particle names in EvtGen as used in .dec decay files.
> Extension of BiMap class beyond mapping of integers

- particle/particle/particle.py
- tests/particle/test_decfilenames.py
- tests/particle/test_particle.py
This greatly simplifies the good-old `Particle.from_dec(...)` method, now that we have converters in the package. It seems natural to rename the method to `Particle.from_evtgen_name` to follow the conventions of the other `_name` properties and methods.
> Rename Particle.from_dec to Particle.from_evtgen_name and use converters

- particle/converters/bimap.py
- particle/geant/geantid.py
- particle/particle/particle.py
- particle/pythia/pythiaid.py
This is a straightforward patch to allow CSV to have comments.
A nicer approach which I can of course also quickly implement is to create a wrapper function for `csv.DictReader`.
The aim is to allow version information or other comments to be added to the CSV files.
> Allow CSV files to have comments starting with #

- particle/pdgid/__init__.py
- particle/pdgid/functions.py
- tests/pdgid/test_functions.py
- tests/pdgid/test_pdgid.py
It turns out that the information stored in a PDG ID is *not* enough to calculate the `C` and `P` quantum numbers. Indeed, for example, `C` is only valid for *unflavoured* mesons and flavourness is not something determinable from the PDG ID.
These quantum numbers are of course available in the `Particle` class, as PDG data, so no worries.
> Remove non-robust C and P properties in PDGID

- particle/particle/particle.py
This way code such as
```
from IPython.display import HTML
HTML(Particle.dump_table(filter_fn=lambda p: p.pdgid.is_meson and p.pdgid.has_strange and p.ctau > 1 * meter, exclusive_fields=['pdgid', 'pdg_name', 'html_name'], tablefmt='html'))
```
works nicely.
> Make Particle.dump_table() work better in notebooks

- particle/particle/particle.py
- tests/particle/test_particle.py
This is relevant to deal e.g. with diquarks.
While at it, the `Particle.empty()` dummy particle got fixed as well, since the definition was not completely what one would expect - it should provide no mass/width info.
> Deal with particles with no mass info

- particle/converters/bimap.py
Fixes
```
particle/converters/bimap.py:8
/Users/hdembinski/Extern/particle/particle/converters/bimap.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Mapping
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```
> fixes collections.abc deprecation warning

- docs/CHANGELOG.rst
- particle/particle/enums.py
- particle/particle/particle.py
- tests/particle/test_particle.py
First stab at this, as per our discussions, @HDembinski and @henryiii.
> Missing and non-relevant particle properties - print-outs made more consistent

- README.rst
- docs/CHANGELOG.rst
- notebooks/ParticleDemo.ipynb
- src/particle/__init__.py
- src/particle/particle/literals.py
- tests/particle/test_literals.py
Fixes https://github.com/scikit-hep/particle/issues/238.
> Make particle literals available from top-level import

- README.rst
The changelog was renamed in [this commit](https://github.com/scikit-hep/particle/commit/7d75b2ce1ebe5d29d47199da96c04626a787f3a0#diff-81baa3f7e3d2d55c8a408032bf865b0f).
> minor fixes in README.rst

- src/particle/pdgid/__init__.py
- src/particle/pdgid/functions.py
- tests/conftest.py
- tests/pdgid/test_functions.py
- tests/pdgid/test_pdgid.py
Indeed, as seen in the PDG  Monte Carlo Particle Numbering Scheme document https://pdg.lbl.gov/2020/reviews/rpp2020-rev-monte-carlo-numbering.pdf, the PDG ID encodes a series of (pseudo)particles or concepts that the code did not yet deal with - these were also not dealt with in the C++ HepPID package.
> New functions for qualification of PDG IDs

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- setup.cfg
- src/particle/particle/particle.py
Add more filter functionality to `Particle.to_list` and `Particle.to_dict` since these 2 methods rely internally on `Particle.findall`, and the latter allows for more arguments than the former methods presently accepted. This PR makes the signatures of these methods match.
> Enhance Particle.to_list and to_dict

- src/particle/particle/enums.py
- tests/particle/test_particle.py
I wanted to some cross-checks with the Julia package [Corpuscles.jl](https://github.com/JuliaPhysics/Corpuscles.jl) and noticed that some particles are not missing in all `particle*.csv` datasets after loading them. E.g. the currently default `particle2020.csv` contains a total of 610 particles, but only 603 are loaded:
```python
>>> from particle import Particle, data
>>> Particle.load_table(data.open_text(data, 'particle2020.csv'))
>>> len(Particle.findall())
603
```
I quickly created a diff to check which particles are missing compared to `Corpuscles.jl` and got:
```julia
julia> [Particle(p) for p in setdiff(Set(corpuscles_ids), Set(particle_ids))]
7-element Array{Particle,1}:
Particle(-203338) Omega(2250)
Particle(-103326) Xi(1950)
Particle(-203316) Xi(2030)
Particle(-103316) Xi(1950) …
```
> Add tests to check if every particle is parsed and added correctly

- .zenodo.json
- MANIFEST.in
As per out chat, @matthewfeickert.
As you can see I'm not filling in all possible fields, e.g. the ones on versioning. I would say we go ahead assuming Zenodo will add the missing fields since anyway it *is* creating at present such a file, on the fly, from best-guesses, as it says on their site.
Let me know if you seen anything obvious missing. Otherwise approve :-). Advance thanks.
> Add a .zenodo.json file

- src/particle/particle/literals.py
- src/particle/particle/utilities.py
- src/particle/pdgid/literals.py
The programmatic names of diquarks such as `(bs)(0)` where returned as `_bs_0`, where the prefix `_` is not so pretty. This PR introduces a trivial adaptation to rather return  `bs_0` and similarly for the other diquarks.
(OK, diquarks are not observed particles so this is largely academic/aesthetics.)
Some temporary variables were also exposed. Now that are removed, the right thing to do.
> Programmatic name for diquarks and SUSY particles

- src/particle/particle/particle.py
Importing particle 0.16.0 takes an unreasonably long time:
```python
In [1]: %time import particle
CPU times: user 12.2 s, sys: 85.2 ms, total: 12.3 s
Wall time: 12.5 s
```
This is due to the use of `if value in cls._table:` inside the `Particle.load_table` which causes it be O(n²) with `Particle.__eq__` currently being called 21,095,760 million times.
This PR does the most backwards compatible fix possible by using a `set` to reduce this down to O(n):
```python
In [1]: %time import particle
CPU times: user 189 ms, sys: 13.7 ms, total: 202 ms
Wall time: 212 ms
```
IMHO a better solution might be to change `Particle._table` to be a `set` but this would change the public API and result in the ordering being lost.
> Fix unreasonably slow import time

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- setup.cfg
This was only missing due to setup-cfg-fmt's default 3.6+, I believe.
> chore: renable missing Python 3.5 support

- setup.cfg
We don't pin flake8-bugbear, and it seems to have a default Python 3 only check. Pretty reasonable now, but we still sadly support Python 2. I'd love to drop all Python 2 support across Scikit-HEP Jan 1, 2022!
> style: ignore a Python 3 only style check

- src/particle/__init__.py
Following from the discussions at https://github.com/scikit-hep/particle/pull/347. Indeed it does not quite make sense to expose at top-level a single converter map from the set of a few defined by default.
Documentation will follow up in the README to expand the usage of converters.
> Do not expose converters in top-level imports

- docs/CHANGELOG.md
- src/particle/particle/particle.py
Following the discussion at https://github.com/scikit-hep/particle/pull/354 and my suggestion, @henryiii and @jonas-eschle. Main reason is that we have `from_pdgid` and `from_evtgen_name` and it seemed awkward not to have `from_name`, the particle name itself.
> Add new class method Particle.from_name

- .pre-commit-config.yaml
- notebooks/ParticleDemo.ipynb
- pyproject.toml
- src/particle/converters/bimap.py
- src/particle/particle/convert.py
- src/particle/particle/kinematics.py
- src/particle/particle/literals.py
- src/particle/particle/particle.py
- src/particle/particle/utilities.py
- src/particle/pdgid/functions.py
- src/particle/pdgid/literals.py
- src/particle/typing.py
- tests/conftest.py
This finishes the typing and uses f-strings everywhere reasonable. Some `type: ignore`'s will go away after the next release of HEPUnits. Some minor polish continuing the removal of Python 2.
- fix(types): full static type checking
- style: switch remaining format strings to f-strings
> fix: full static typing

- .github/workflows/ci.yml
- docs/CHANGELOG.md
- src/particle/corsika/corsika7id.py
- src/particle/lhcb/functions.py
- src/particle/particle/particle.py
- tests/particle/test_generation.py
It turns out that doctests were in fact not being run. This update adds an explicit step for doctests.
With this I can see several docstrings that needed updates for PDG 2022 mass values, for example.
> Actually run doctests with pytest

- noxfile.py
This was generating .pyc files for all packages; those are not needed (since they will target only one version of Python - 3.7 in this case).
> chore: clean up zipfile

- README.rst
Closes: https://github.com/scikit-hep/particle/issues/476
This fixes the example such that we only get quarkonia 
```
>>> print ([p.quarks for p in Particle.finditer(lambda p: len(p.quarks)==2 and p.quarks[0] == p.quarks[1].swapcase())])
['cC', 'cC', 'cC', 'bB', 'bB', 'cC', 'cC', 'bB', 'bB', 'cC', 'bB', 'bB', 'cC', 'cC', 'cC', 'cC', 'bB', 'bB', 'bB', 'bB', 'bB', 'bB', 'cC', 'bB', 'cC', 'bB', 'cC']
>>> print ([p.quarks for p in Particle.finditer(lambda p: is_meson(p.pdgid) and is_heavy_flavor(p.pdgid) and p.is_self_conjugate)])
['cC', 'cC', 'cC', 'bB', 'bB', 'cC', 'cC', 'bB', 'bB', 'cC', 'bB', 'bB', 'cC', 'cC', 'cC', 'cC', 'bB', 'bB', 'bB', 'bB', 'bB', 'bB', 'cC', 'bB', 'cC', 'bB', 'cC']
```
instead of what current example produces
```
>>> print ([p.quarks for p in Particle.finditer(lambda …
```
> Fix is_quarkonium in Readme

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/particle/_compat/typing.py
- src/particle/_compat/warnings.py
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- src/particle/typing.py
This is available in `typing_extensions` already and will be in CPython 3.13, and unlike the third-party package, typing tools can tell this is deprecated (mypy soon, some other typing checkers already support it).
This also enables us to start testing on 3.12 in a followup (fixes a warning importing Traversable).
> fix: replace deprecated package with Python 3.13 deprecated decorator

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.rst
- pyproject.toml
- src/particle/__init__.py
- src/particle/particle/particle.py
Modernize Ruff config. ~~Waiting on the next release (which adds better Jupyter notebook support) for ruff-format.~~ (Now released)
See https://github.com/scientific-python/cookie/pull/299.
> chore: modernize Ruff config, use ruff-format

- .gitignore
- environment.yml
- notebooks/ParticleDemo.ipynb
- pyproject.toml
This uses the new pixi 0.18 support for editable installs and pyproject.toml. I left the classic environment.yml in for Binder for now - we can remove it if binder starts supporting it. It's mostly experimental at this point, but it seems to work pretty well. I have not committed the lockfile yet since we aren't using it anywhere at the moment.
> chore: add pixi support

- src/particle/particle/particle.py
- tests/particle/test_particle.py
Some particle names with a "prime" were not properly displayed in HTML whereas they were in LaTeX.
> Better testing of HTML particle names

- .github/workflows/ci.yml
The Codecov token was missing as a secret. Added now.
> Get Codecov to upload again

- src/particle/particle/particle.py
- tests/particle/test_particle.py
I added two dicts that are build at import time, one mapping one pdgid to the alternative representation to implement the comparison and one with the "preferred" pdgid used for `__hash__` and to make `from_name` work and always return the same pdgid.
> I chose the "bag of quarks" ids for the "preferred" options, for no particular reason.
Edit: that's actually the official recommendation:
> To avoid ambiguities, nuclear codes should not be applied to a single hadron, like p, n or Λ0, where quark-contents-based codes already exist.
From that I infer though, that neutron and proton are not the only cases, also the delta resonance at least.
Closes https://github.com/scikit-hep/particle/issues/620.
> Make sure neutron, proton and their anti-particles compare equal

- .github/workflows/cd.yml
The PyPI ones are not persisted yet, but they are checked.
> ci: add attestations

- src/particle/particle/particle.py
- src/particle/particle/utilities.py
- tests/particle/test_utilities.py
Closes https://github.com/scikit-hep/particle/issues/667.
> Fix the creation of programmatic names for nuclei when the nucleus names end with a 0
