scikit-hep/particle

- README.rst
- hepparticle/__init__.py
- setup.py
- tests/pdgid/test_functions.py
- tests/pdgid/test_pdgid.py
- tests/test_hepparticle.py
Renaming of package name and update of URLs.
> Preparation of move to the Scikit-HEP organisation

- particle/pdgid/functions.py
- particle/pdgid/pdgid.py
This fixes Python 3 + Particle bugs with division.
> Fix for Python 3

- azure-pipelines.yml
Giving it a go … Fingers crossed!
> Set-up Azure tests on Windows

- particle/particle/particle.py
- setup.py
- tests/particle/test_particle.py
> Some 0.2.1 fixes

- setup.py
Closes https://github.com/scikit-hep/particle/issues/55.
> setup.py file fixed to actually ship the data files

- README.rst
- particle/particle/particle.py
- tests/particle/test_particle.py
More Pythonic search (the original function was designed around the orignal Pandas table). Some examples of usage:
```python
Particle.from_search_list(lambda p: p.name == 'p')
Particle.from_search_list(name = 'p')
Particle.from_search_list(name = lambda x: x == 'p')
Particle.from_search_list(lambda x: x.name == 'p' and x > 0)
Particle.from_search_list(name = 'p', particle=True)
Particle.from_search_list('p')
Particle.from_search_list(fullname = lambda x: 'p' in x)
Particle.from_search_list(lifetime = lambda x : x > 1*second) 
```
> Adding new, more powerful search

- particle/particle/particle.py
Addresses https://github.com/scikit-hep/particle/issues/50.
> Fuller documentation of Particle class

- particle/pdgid/functions.py
- particle/pdgid/pdgid.py
- tests/conftest.py
- tests/pdgid/test_functions.py
I fixed 2 auxiliary functions while at it ...
> Finalise documentation of pdgid submodule

- README.rst
- particle/particle/particle.py
As agreed in issue https://github.com/scikit-hep/particle/issues/71.
> Remove Particle.radius property

- tests/particle/test_enums.py
- tests/particle/test_particle.py
Addresses "issue" https://github.com/scikit-hep/particle/issues/88.
> Test of particle.enums moved to dedicated test_enums.py file

- particle/particle/particle.py
- tests/particle/test_particle.py
Addresses https://github.com/scikit-hep/particle/issues/87.
> Better print-out of Particle properties

- README.rst
- docs/CHANGELOG.rst
- particle/particle/convert.py
- particle/particle/particle.py
- tests/particle/test_particle.py
OK, we're now fully consistent.
> Particle name-related methods made yet more consistent

- README.rst
- particle/particle/convert.py
- particle/particle/enums.py
- particle/particle/particle.py
Seem more natural names for what they reflect.
> Improvement to Enum defining what happens when a particle is inverted

- docs/CHANGELOG.rst
- particle/version.py
New release with major improvements compared to version 0.3.0.
> Bump to version 0.4.0

- README.rst
- particle/__main__.py
Addresses issue https://github.com/scikit-hep/particle/issues/91 - basically a typo in the documentation.
I now added some examples to the help printout.
> Clarify usage of python -m particle {search,pdgid}

- docs/CHANGELOG.rst
- particle/version.py
I reckon we can merge and tag once https://github.com/scikit-hep/particle/pull/119 is merged.
> Release version 0.4.3

- __main__.py
- particle/__init__.py
- particle/__main__.py
- setup.cfg
- setup.py
Some cleanup, working on a new use method.
> Setup improvements

- .ci/azure-zipapp.yml
- azure-pipelines.yml
- particle/__main__.py
- particle/particle/enums.py
This adds zipapp production to the CI.
> Adding zipapp CI

- notebooks/ParticleDemo.ipynb
Henry, I made some trivial updates to the notebook, which I find relevant:
- Better have text bold than green text that is not displayed when people have a look at the notebook online.
- Some bits highlighted as code.
> Demo notebook update

- particle/particle/convert.py
- particle/particle/particle.py
- setup.py
> Improve exception from, drop single six usage without requirements

- environment.yml
- particle/particle/convert.py
- particle/particle/particle.py
- requirements-dev.txt
- requirements.txt
- setup.py
- tests/pdgid/test_functions.py
Addresses https://github.com/scikit-hep/particle/issues/135.
> Addition of Particle.dump_table(...) method

- README.rst
> Funding acknowlegment

- particle/__init__.py
- particle/particle/__init__.py
As per your request, @daritter.
> Make InvalidParticle available at top-level import

- particle/particle/particle.py
Closes https://github.com/scikit-hep/particle/issues/185.
Would this work for you @daritter and @mayou36?
> Store dummy/unknown width and lifetime errors as None

- docs/CHANGELOG.rst
- particle/data/README.rst
- particle/data/conversions.csv
- particle/data/pdgid_to_evtgenname.csv
- particle/data/pdgid_to_geantid.csv
- particle/data/pdgid_to_latexname.csv
- particle/data/pdgid_to_pythiaid.csv
- particle/particle/convert.py
- tests/particle/test_generation.py
FYI @tamasgal and @henryiii, following from https://github.com/scikit-hep/particle/pull/192/.
How about this versioning "scheme"?
I profited from the occasion to rename a file so that it better follows the convention of the other CSV files.
> Add versioning to data CSV files

- docs/CHANGELOG.rst
- particle/particle/particle.py
- tests/particle/test_particle.py
These are self-consistency checks.
> More tests for particle P and C quantum numbers

- docs/CHANGELOG.rst
- particle/_version.py
- particle/data/README.rst
- particle/geant/geant3id.py
Follows comment in https://github.com/scikit-hep/particle/issues/206.
> Better doc for Geant3ID class

- docs/CHANGELOG.rst
- particle/particle/particle.py
> Particle class: Minor fix to class method from_evtgen_name(...), more doc

- .ci/azure-steps.yml
- setup.py
- tests/particle/test_particle.py
> Some tests for Particle.dump_table()

- particle/particle/particle.py
- requirements-dev.txt
- requirements.txt
- setup.py
> fix attr.s deprecation

- .github/workflows/ci.yml
- CONTRIBUTING.md
- MANIFEST.in
- setup.cfg
> Adding contributing

- .github/workflows/ci.yml
- .gitignore
> Test Jupyter notebooks

- README.rst
The how to do this came up in discussions.
> Expand info in README on custom data loading

- notebooks/ParticleDemo.ipynb
Fixes https://github.com/scikit-hep/particle/issues/136.
> A tiny bit more info into the demo notebook

- .ci/azure-steps.yml
- .github/workflows/ci.yml
- docs/CHANGELOG.md
- setup.cfg
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- tests/particle/test_particle.py
Addresses https://github.com/scikit-hep/particle/issues/233.
> Replace Particle.dump_table with Particle.to_dict to remove strong coupling in that method

- README.rst
- docs/CHANGELOG.md
- src/particle/pdgid/__init__.py
- src/particle/pdgid/functions.py
- tests/pdgid/test_functions.py
- tests/pdgid/test_pdgid.py
Fixes https://github.com/scikit-hep/particle/issues/259.
> More PDG ID qualification functions

- README.rst
- src/particle/pdgid/__init__.py
- src/particle/pdgid/functions.py
Closes https://github.com/scikit-hep/particle/issues/266.
> Remove broken HepPDT link

- docs/CHANGELOG.md
FYI @henryiii - it was time to release a new version given all changes wrt 0.11.
> Release v0.12.0

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- src/particle/converters/bimap.py
- src/particle/particle/kinematics.py
- tests/particle/test_particle.py
Forgot to make this PR earlier.
> ci: publish and adapt to updates of physical constants in hepunits 2.0.0

- .pre-commit-config.yaml
- MANIFEST.in
- docs/CHANGELOG.md
- setup.cfg
- src/particle/__main__.py
- src/particle/converters/bimap.py
- src/particle/data/__init__.py
- src/particle/geant/geant3id.py
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- src/particle/pdgid/pdgid.py
- src/particle/pythia/pythiaid.py
This adds full static typing, including for external users. Followup of sorts to #274.
- feat: better support for static types
- feat: type the rest of the code
- feat: support external type checking
> feat: static typing

- README.rst
- docs/CHANGELOG.md
- src/particle/particle/literals.py
- src/particle/pdgid/literals.py
- src/particle/shared_literals.py
- tests/particle/test_utilities.py
Seems the better thing to do :-).
> Particle and PDG ID literals for all particles in the latest data file

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> ci: follow guidelines more closely

- README.rst
- noxfile.py
- setup.cfg
- src/particle/converters/bimap.py
- src/particle/converters/evtgen.py
- src/particle/data/README.rst
- src/particle/data/__init__.py
- src/particle/geant/geant3id.py
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- src/particle/pythia/pythiaid.py
- src/particle/typing.py
- tests/converters/test_maps.py
- tests/particle/test_generation.py
- tests/particle/test_particle.py
Addressing https://github.com/scikit-hep/decaylanguage/issues/138 (but for particle).
A few other bits of cleanup. Adding a noxfile too to make it easier to run.
> chore: use newer files interface

- .pre-commit-config.yaml
- setup.cfg
- src/particle/__init__.py
- src/particle/converters/__init__.py
- src/particle/converters/bimap.py
- src/particle/geant/__init__.py
- src/particle/geant/geant3id.py
- src/particle/particle/__init__.py
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- src/particle/particle/utilities.py
- src/particle/pdgid/__init__.py
- src/particle/pythia/__init__.py
- src/particle/pythia/pythiaid.py
- tests/converters/test_maps.py
- tests/geant/test_geant3id.py
- tests/particle/test_convert.py
- tests/particle/test_generation.py
- tests/particle/test_particle.py
- tests/particle/test_utilities.py
- tests/pdgid/test_functions.py
- tests/pdgid/test_pdgid.py
- tests/pythia/test_pythiaid.py
Will put a few comments inline.
> style: make changes suggested by flake8

- docs/CHANGELOG.md
- src/particle/particle/particle.py
- tests/particle/test_particle.py
Closes #312. Containership testing will be slower, but findall will likely be faster (not that anything is very slow).
> feat: add finditer

- .pre-commit-config.yaml
- notebooks/ParticleDemo.ipynb
1-2 lines might be a tiny bit worse, but having Black on the notebooks is really nice too.
> style: enforce black on notebooks

- .github/workflows/ci.yml
- docs/CHANGELOG.md
Closes https://github.com/scikit-hep/particle/issues/325
> Ressurect tests on "all" platforms - Linux, macOS and Windows

- README.rst
Closes https://github.com/scikit-hep/particle/issues/331
> Better coverage of documentation for Particle methods

- noxfile.py
- setup.cfg
- src/particle/converters/bimap.py
- src/particle/particle/particle.py
- tests/particle/test_performance.py
This should improve the performance of `from_pdgid` by using a hashed lookup instead of a linear search. Closes #348.
> refactor: faster from_pdgid

- src/particle/particle/utilities.py
- tests/particle/test_particle.py
Closes https://github.com/scikit-hep/particle/issues/361.
> HTML Greek letters to use hex code rather than entity name

- README.rst
- docs/CHANGELOG.md
- src/particle/lhcb/converters/__init__.py
- src/particle/lhcb/converters/lhcb.py
- src/particle/lhcb/utils.py
Closes https://github.com/scikit-hep/particle/issues/365.
> Documentation on new LHCb-specific module

- MANIFEST.in
Is it as simple as that? cc @henryiii .
Closes #386.
> MANIFEST.in: Include tests in sdist

- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
- setup.cfg
- src/particle/converters/bimap.py
- src/particle/particle/particle.py
This captures the good parts of #382, without trying to be more clever with config.
> chore: minor cleanup and updates

- src/particle/particle/convert.py
Fixes test failures provoked by the pre-commit update in PR https://github.com/scikit-hep/particle/pull/416.
> Adapt to Pandas 1.5

- README.rst
- src/particle/particle/convert.py
Noticed a few things working on decaylanguage.
> chore: minor followup cleanup for 3.6

- src/particle/__main__.py
- src/particle/converters/bimap.py
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- src/particle/pdgid/functions.py
Some suggestions using `reverb`.
> chore: cleanup with reverb suggestions

- .github/matchers/pylint.json
- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
- src/particle/converters/bimap.py
- src/particle/data/__init__.py
- src/particle/lhcb/data/__init__.py
- src/particle/particle/convert.py
- src/particle/particle/kinematics.py
- src/particle/particle/particle.py
- src/particle/pdgid/functions.py
- src/particle/typing.py
> chore: add pylint

- tests/particle/test_particle.py
FYI @The-Ludwig I'm here improving the tests for the `Particle.from_nucleus_info()` method you enhanced the package with. We now have full coverage of the method.
> Full test of Particle.from_nucleus_info() method

- README.rst
Closes https://github.com/scikit-hep/particle/issues/107.
> docs: Add basic documentation on how to create user-defined particles

- src/particle/data/__init__.py
- src/particle/lhcb/data/__init__.py
- tests/test_module_apis.py
- tests/test_package.py
Trivial addition but nicer to show a better coverage.
> Add tests of module APIs

- src/particle/corsika/corsika7id.py
- tests/corsika/test_corsika7id.py
This adds more tests to enhance the coverage of the `Corsika7` module to 100%. 
Additionally some docstrings got minor changes to enhance the documentation. 
I also refactored `Corsika7ID.name()` to eliminate dead code.
> Enhance code coverage for Corsika7 module

- README.rst
- src/particle/data/README.rst
- src/particle/particle/particle.py
- tests/particle/test_particle.py
- tests/particle/test_performance.py
Following up from PR https://github.com/scikit-hep/particle/pull/466.
> Make CSV data files version 12 the default (updates on nuclei)

- .flake8
- .pre-commit-config.yaml
- admin/dump_pdgid_to_corsika7.py
- pyproject.toml
- src/particle/converters/bimap.py
- src/particle/particle/convert.py
- src/particle/particle/particle.py
- src/particle/pdgid/functions.py
- tests/lhcb/test_lhcb_name.py
- tests/particle/test_convert.py
- tests/particle/test_generation.py
- tests/particle/test_kinematics.py
- tests/particle/test_particle.py
- tests/particle/test_utilities.py
- tests/pdgid/test_functions.py
- chore: move to using Ruff
- style: run Ruff
- chore: suggestions and fixes from Ruff
> chore: move to Ruff

- .pre-commit-config.yaml
- pyproject.toml
- src/particle/__main__.py
- src/particle/particle/particle.py
- tests/particle/test_particle.py
Follow-up from discussion at https://github.com/scikit-hep/particle/pull/352#issuecomment-961138684.
> Deprecate Particle methods from_string and from_string_list

- src/particle/particle/convert.py
- tests/particle/test_generation.py
Ensure no fishy mass=None appear except for non-known particles and special particles.
> Add test for None masses

- src/particle/pdgid/functions.py
- tests/conftest.py
- tests/pdgid/test_functions.py
This PR aims to fix #463 
@eduardo-rodrigues 
This is a proposed solution. There is some work to be done for example to check if the spin of all sfermions is indeed zero. As of now PR only fixes the issue with sfermions and not with gluinos. 
Please let me know if the strategy is okay  
Thanks
> Fix j_spin for susy particle

- docs/CHANGELOG.md
To pick up the 2023 PDG data file.
> Prepare for release 0.23.0

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- README.md
- environment.yml
- noxfile.py
- pyproject.toml
- src/particle/_compat/typing.py
- src/particle/typing.py
- tests/test_module_apis.py
- **chore: drop Python 3.7, add Python 3.12**
> chore: require Python 3.8+

- .github/workflows/cd.yml
See https://github.com/scikit-hep/particle/pull/590.
> ci: use PyPI trusted publisher

- .github/workflows/cd.yml
> ci: fix release file upload

- .github/workflows/ci.yml
- pyproject.toml
3.13 final is releasing on Tuesday.
> chore: test on Python 3.13

- src/particle/pdgid/functions.py
> fix: higgs j_spin is zero

- src/particle/pdgid/functions.py
Closes https://github.com/scikit-hep/particle/issues/671.
> Improve helper PDGID related _digit function
